apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hpa-demo
  region: us-east-1
  version: "1.28"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
- name: generic-workload
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true