apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
stringData:
  #   --> openssl rand -hex 32
  N8N_ENCRYPTION_KEY: "65f3fa6968ecff557d7855769a85f20344395a5511a7963290c9d893e2783f24"
